// lib/countries.js
// Full country / nationality list (ISO-inspired, simplified for UI & Firestore)

export const COUNTRIES = [
  { value: 'afghan', label: 'Afghanistan' },
  { value: 'albanian', label: 'Albania' },
  { value: 'algerian', label: 'Algeria' },
  { value: 'andorran', label: 'Andorra' },
  { value: 'angolan', label: 'Angola' },
  { value: 'antiguan', label: 'Antigua and Barbuda' },
  { value: 'argentine', label: 'Argentina' },
  { value: 'armenian', label: 'Armenia' },
  { value: 'australian', label: 'Australia' },
  { value: 'austrian', label: 'Austria' },
  { value: 'azerbaijani', label: 'Azerbaijan' },

  { value: 'bahamian', label: 'Bahamas' },
  { value: 'bahraini', label: 'Bahrain' },
  { value: 'bangladeshi', label: 'Bangladesh' },
  { value: 'barbadian', label: 'Barbados' },
  { value: 'belarusian', label: 'Belarus' },
  { value: 'belgian', label: 'Belgium' },
  { value: 'belizean', label: 'Belize' },
  { value: 'beninese', label: 'Benin' },
  { value: 'bhutanese', label: 'Bhutan' },
  { value: 'bolivian', label: 'Bolivia' },
  { value: 'bosnian', label: 'Bosnia and Herzegovina' },
  { value: 'botswanan', label: 'Botswana' },
  { value: 'brazilian', label: 'Brazil' },
  { value: 'british', label: 'United Kingdom' },
  { value: 'bruneian', label: 'Brunei' },
  { value: 'bulgarian', label: 'Bulgaria' },
  { value: 'burkinabe', label: 'Burkina Faso' },
  { value: 'burundian', label: 'Burundi' },

  { value: 'cambodian', label: 'Cambodia' },
  { value: 'cameroonian', label: 'Cameroon' },
  { value: 'canadian', label: 'Canada' },
  { value: 'cape_verdean', label: 'Cape Verde' },
  { value: 'central_african', label: 'Central African Republic' },
  { value: 'chadian', label: 'Chad' },
  { value: 'chilean', label: 'Chile' },
  { value: 'chinese', label: 'China' },
  { value: 'colombian', label: 'Colombia' },
  { value: 'comoran', label: 'Comoros' },
  { value: 'congolese', label: 'Congo' },
  { value: 'costa_rican', label: 'Costa Rica' },
  { value: 'croatian', label: 'Croatia' },
  { value: 'cuban', label: 'Cuba' },
  { value: 'cypriot', label: 'Cyprus' },
  { value: 'czech', label: 'Czech Republic' },

  { value: 'danish', label: 'Denmark' },
  { value: 'djiboutian', label: 'Djibouti' },
  { value: 'dominican', label: 'Dominican Republic' },

  { value: 'ecuadorean', label: 'Ecuador' },
  { value: 'egyptian', label: 'Egypt' },
  { value: 'emirati', label: 'United Arab Emirates' },
  { value: 'equatorial_guinean', label: 'Equatorial Guinea' },
  { value: 'eritrean', label: 'Eritrea' },
  { value: 'estonian', label: 'Estonia' },
  { value: 'ethiopian', label: 'Ethiopia' },

  { value: 'fijian', label: 'Fiji' },
  { value: 'finnish', label: 'Finland' },
  { value: 'french', label: 'France' },

  { value: 'gabonese', label: 'Gabon' },
  { value: 'gambian', label: 'Gambia' },
  { value: 'georgian', label: 'Georgia' },
  { value: 'german', label: 'Germany' },
  { value: 'ghanaian', label: 'Ghana' },
  { value: 'greek', label: 'Greece' },
  { value: 'grenadian', label: 'Grenada' },
  { value: 'guatemalan', label: 'Guatemala' },
  { value: 'guinean', label: 'Guinea' },
  { value: 'guyanese', label: 'Guyana' },

  { value: 'haitian', label: 'Haiti' },
  { value: 'honduran', label: 'Honduras' },
  { value: 'hungarian', label: 'Hungary' },

  { value: 'icelandic', label: 'Iceland' },
  { value: 'indian', label: 'India' },
  { value: 'indonesian', label: 'Indonesia' },
  { value: 'iranian', label: 'Iran' },
  { value: 'iraqi', label: 'Iraq' },
  { value: 'irish', label: 'Ireland' },
  { value: 'israeli', label: 'Israel' },
  { value: 'italian', label: 'Italy' },

  { value: 'jamaican', label: 'Jamaica' },
  { value: 'japanese', label: 'Japan' },
  { value: 'jordanian', label: 'Jordan' },

  { value: 'kazakh', label: 'Kazakhstan' },
  { value: 'kenyan', label: 'Kenya' },
  { value: 'kuwaiti', label: 'Kuwait' },
  { value: 'kyrgyz', label: 'Kyrgyzstan' },

  { value: 'laotian', label: 'Laos' },
  { value: 'latvian', label: 'Latvia' },
  { value: 'lebanese', label: 'Lebanon' },
  { value: 'liberian', label: 'Liberia' },
  { value: 'libyan', label: 'Libya' },
  { value: 'lithuanian', label: 'Lithuania' },
  { value: 'luxembourgish', label: 'Luxembourg' },

  { value: 'malagasy', label: 'Madagascar' },
  { value: 'malawian', label: 'Malawi' },
  { value: 'malaysian', label: 'Malaysia' },
  { value: 'maldivian', label: 'Maldives' },
  { value: 'malian', label: 'Mali' },
  { value: 'maltese', label: 'Malta' },
  { value: 'mauritanian', label: 'Mauritania' },
  { value: 'mauritian', label: 'Mauritius' },
  { value: 'mexican', label: 'Mexico' },
  { value: 'moldovan', label: 'Moldova' },
  { value: 'mongolian', label: 'Mongolia' },
  { value: 'montenegrin', label: 'Montenegro' },
  { value: 'moroccan', label: 'Morocco' },
  { value: 'mozambican', label: 'Mozambique' },
  { value: 'myanmarese', label: 'Myanmar' },

  { value: 'namibian', label: 'Namibia' },
  { value: 'nepalese', label: 'Nepal' },
  { value: 'dutch', label: 'Netherlands' },
  { value: 'new_zealander', label: 'New Zealand' },
  { value: 'nicaraguan', label: 'Nicaragua' },
  { value: 'nigerian', label: 'Nigeria' },
  { value: 'north_korean', label: 'North Korea' },
  { value: 'norwegian', label: 'Norway' },

  { value: 'omani', label: 'Oman' },

  { value: 'pakistani', label: 'Pakistan' },
  { value: 'panamanian', label: 'Panama' },
  { value: 'peruvian', label: 'Peru' },
  { value: 'philippine', label: 'Philippines' },
  { value: 'polish', label: 'Poland' },
  { value: 'portuguese', label: 'Portugal' },

  { value: 'qatari', label: 'Qatar' },

  { value: 'romanian', label: 'Romania' },
  { value: 'russian', label: 'Russia' },
  { value: 'rwandan', label: 'Rwanda' },

  { value: 'saudi', label: 'Saudi Arabia' },
  { value: 'senegalese', label: 'Senegal' },
  { value: 'serbian', label: 'Serbia' },
  { value: 'singaporean', label: 'Singapore' },
  { value: 'slovak', label: 'Slovakia' },
  { value: 'slovenian', label: 'Slovenia' },
  { value: 'somali', label: 'Somalia' },
  { value: 'south_african', label: 'South Africa' },
  { value: 'south_korean', label: 'South Korea' },
  { value: 'spanish', label: 'Spain' },
  { value: 'sri_lankan', label: 'Sri Lanka' },
  { value: 'sudanese', label: 'Sudan' },
  { value: 'swedish', label: 'Sweden' },
  { value: 'swiss', label: 'Switzerland' },
  { value: 'syrian', label: 'Syria' },

  { value: 'taiwanese', label: 'Taiwan' },
  { value: 'tajik', label: 'Tajikistan' },
  { value: 'tanzanian', label: 'Tanzania' },
  { value: 'thai', label: 'Thailand' },
  { value: 'tunisian', label: 'Tunisia' },
  { value: 'turkish', label: 'Turkey' },
  { value: 'turkmen', label: 'Turkmenistan' },

  { value: 'ugandan', label: 'Uganda' },
  { value: 'ukrainian', label: 'Ukraine' },
  { value: 'american', label: 'United States' },
  { value: 'uruguayan', label: 'Uruguay' },
  { value: 'uzbek', label: 'Uzbekistan' },

  { value: 'venezuelan', label: 'Venezuela' },
  { value: 'vietnamese', label: 'Vietnam' },

  { value: 'yemeni', label: 'Yemen' },

  { value: 'zambian', label: 'Zambia' },
  { value: 'zimbabwean', label: 'Zimbabwe' },

  { value: 'other', label: 'Other' }
]
